---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
---
engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
exclude_paths:
  - spec/**/*
